version: '3.8'

services:
  mysql:
    build: ./Data
    container_name: mysql
    environment:
      MYSQL_DATABASE: pentest_final
      MYSQL_USER: linh
      MYSQL_PASSWORD: linh
      MYSQL_ROOT_PASSWORD: "linh"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - vulnapp_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-plinh"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    image: melp007/vulnapp:latest
    build: 
      context: .
      dockerfile: "dockerfile.v3"
      # dockerfile: "dockerfile.v2"
      # dockerfile: "dockerfile.v1"
    container_name: vulnapp
    ports:
      - "80:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/pentest_final
      - DB_USER=root
      - DB_PASSWORD=linh
    networks:
      - vulnapp_network

volumes:
  mysql_data:

networks:
  vulnapp_network:
